# Generated by Django 4.2.5 on 2023-09-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_user_alter_task_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-deadline']},
        ),
    ]
