# Generated by Django 4.2.5 on 2023-09-24 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_task_user_alter_topic_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='user',
        ),
        migrations.DeleteModel(
            name='Subtask',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
