# Generated by Django 4.2.5 on 2023-09-24 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact',
        ),
    ]
