# Generated by Django 4.2.5 on 2023-09-28 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_subtask_date_of_completion_task_date_of_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='date_of_completion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 22, 4, 53, 575589)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_of_completion',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 22, 4, 53, 572544)),
        ),
    ]
