# Generated by Django 4.2.5 on 2023-10-02 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_subtask_date_of_completion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='date_of_completion',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 2, 22, 22, 6, 623118)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_of_completion',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 2, 22, 22, 6, 621180)),
        ),
    ]
