# Generated by Django 4.2.5 on 2023-10-07 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_reviews_title_alter_subtask_date_of_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='date_of_completion',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 7, 9, 17, 41, 523610)),
        ),
    ]
